async_test.out:async_test.c
	g++ -o async_test.out async_test.c -std=c++11 -pthread
	./async_test.out
bp_decoder_test.out:bp_decoder_test.c bp_decoder.h
	g++ -o bp_decoder_test.out bp_decoder_test.c bp_decoder.h
