async_test.out:async_test.c
	g++ -o async_test.out async_test.c -std=c++11 -pthread
	./async_test.out
bp_decoder_test.out:bp_decoder_test.c bp_decoder.h
	g++ -o bp_decoder_test.out bp_decoder_test.c bp_decoder.h
ctpl_test.out:ctpl_test.c
	g++ -std=c++11 -pthread -o ctpl_test.out ctpl_test.c
openmp_test.out:openmp_test.c
	g++ -o openmp_test.out openmp_test.c -fopenmp -std=c++11
